version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      versioning-strategy: increase
      schedule:
          interval: daily
          time: "21:05"
          timezone: Indian/Maldives	
