name: NPM Delete
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Deprecate 
        run: npm remove discord-portable-player@1.2.0 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
