name: NPM Deprecate
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Deprecate 
        run: npm deprecate discord-portable-player@2.0.0-dev.1655378962.02c7e62 "No longer supported. Install the latest dev release!"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
