name: NPM Deprecate
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Deprecate 
        run: npm deprecate discord-portable-player@2.0.11 "No longer supported. Install the latest release!"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
