name: Publish 
on:
  workflow_dispatch:
jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: stable

      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Publish
        run: |
          npx tsc --skipLibCheck
          npm version --git-tag-version=false $(jq --raw-output '.version' package.json)
          npm publish || true 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
